### ISSUE TITLE
cron_kubernetes: command not found

### ISSUE THREAD

**Issue by laranicolas** [keylimetoolbox/cron-kubernetes-ruby#5]
Hey,

I am using your gem but after configured and installed everything, weird but I couldn't run the main command `cron_kubernetes`, any idea?

Bash:
```
cron_kubernetes --configuration config/initializers/cron_kubernetes.rb --schedule config/schedule.rb
-bash: cron_kubernetes: command not found
```

Gemfile.lock:

```
    cron-kubernetes (1.1.0)
      kubeclient (>= 3.1.2, < 5.0)
```

Cheers.

**Comment by jeremywadsack** [comment]
Hi @laranicolas. Did you install this with `bundler`? You might need to use `bundle exec cron_kubernetes ...`.

**Comment by laranicolas** [comment]
You were right, added `bundle exec` and worked. Deployed from local to production the cron jobs but they are running with the local path.

Which would be the expected flow to deploy on production, I have run in a rails pod in Digital k8s but get it an error from kubeclient (please see the below image):

<img width="1418" alt="Screen Shot 2020-12-21 at 12 17 59" src="https://user-images.githubusercontent.com/1824473/102792026-a9e57d00-4386-11eb-8983-adc931e484c4.png">

**Comment by laranicolas** [comment]
Hey,

When deploying from local I am getting all cron jobs deployed perfectly but I should replace the image from the manifest template right? and how could I update the job command path? because I am checking on production and jobs are using the local path to run the jobs:

i.e:

```
Command:
/bin/bash
-l
-c
cd local_path && bundle exec rake task --silent
```

manifest:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: scheduled-job
spec:
  template:
    metadata:
      name: scheduled-job
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: run-cron-kubernetes-gem
        image: rails_app_image
      restartPolicy: OnFailure
```

**Comment by jeremywadsack** [comment]
@laranicolas The screen shot you provided shows a permissions error. So you'll need to update permissions on the service account you have for the deployment process to provide `list` for `cronjobs.batch` (or provide a canned role that covers this).

> I should replace the image from the manifest template
I'm not sure I understand the question here. The image would be used for all cron-jobs. Are you saying you want a different image for different job types? (It's a reasonable requests but not one that's currently supported.)


> how could I update the job command path? because I am checking on production and jobs are using the local path to run the jobs

The job path will use either `Rails.root` (if running under Rails) or the current directory:

https://github.com/keylimetoolbox/cron-kubernetes-ruby/blob/b71e7bddb8b8b1e0e50a32fe6a76a63bd3072914/lib/cron_kubernetes/scheduler.rb#L59-L62

I think the problem is that you need to run the `cron_kubernetes` _in your production environment_ not in your local development. For example, you can launch/run a pod in you cluster and run the command there. Or run it from one of your existing containers after deployment.

Let me know if that's on the mark or if we need to look at something else.

**Comment by laranicolas** [comment]
@jeremywadsack thanks for your explanation.

I configured the permissions for the cluster and now I could run the gem.

Now I am having some issues with the jobs, they are failing with the above issue:

```
/bin/bash: line 0: cd: /app: No such file or directory
```

Seems jobs are not using the image I passed in the template? `app` is the base docker directory.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: scheduled-job
spec:
  template:
    metadata:
      name: scheduled-job
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: run-cron-kubernetes-gem
        image: my_image
      # restartPolicy: OnFailure
      restartPolicy: Never
```

Any thought?
